### PR TITLE
(Hopefully) fixed #105

### LINKED ISSUE #105: Crash in thinkpad-dock when sound:unmute ist set
Hi.

thinkpad-dock crashes for me when I do not set [sound] unmute = false in the config file.

This is the output I get:

> thinkpad-dock
> /usr/lib/python3/dist-packages/pkg_resources/__init__.py:1224: UserWarning: /home/xxxx/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
>   warnings.warn(msg, UserWarning)
> Erhalten der Sink-Informationen fehlgeschlagen: Entität nicht vorhanden
> Traceback (most recent call last):
>   File "/usr/local/bin/thinkpad-dock", line 9, in <module>
>     load_entry_point('thinkpad-scripts==4.4.0', 'console_scripts', 'thinkpad-dock')()
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/dock.py", line 220, in main
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/dock.py", line 116, in dock
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/sound.py", line 29, in unmute
>   File "/usr/local/lib/python3.4/dist-packages/thinkpad_scripts-4.4.0-py3.4.egg/tps/__init__.py", line 134, in wrapper
>   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['pactl', 'set-sink-volume', '0', '100%']' returned non-zero exit status 1

### PR DESCRIPTION
**Pull request by Aruee**
You said you didn't have time, this should do it :).

### CODE REVIEW

**Comment by jturner314** [comment]
This looks like it'll work, and I think it's the right approach to simply adjust the volume of all the sinks. A couple of comments:

* ``pactl`` is probably preferable to ``pacmd`` simply because we're already using it elsewhere.
* It may be simpler to use regular expressions than the ``get_pulseaudio_sinks()`` function. Something like:

  ```python
  sink_output = tps.check_output(['pactl', 'list', 'sinks'], logger).decode()
  sinks = re.findall('^Sink #(\d+)$', sink_output, flags=re.MULTILINE)
  ```

  would work.

**Comment by Aruee** [comment]
Using pactl instead of pacmd does work as you suggested, see 4da0b10 in my fork.

I'm not really a fan of regexes. I know that they can do all kinds of stuff using one-liners. They are, however, not well-readable and a pain to debug, so I usually avoid them at all costs.

I thought that the get_pulseaudio_sinks() method would integrate well with the existing code, using the input.py to interface with the underlying system using specific methods for each task. If you'd prefer to use regexes I'd prefer not to write them as I really don't have much experience with them and not enough time on my hands to struggle my way through writing a good, error-free one.

**Comment by martin-ueding** [comment]
Thank you for your patch! It is a very good idea to let Pulse Audio enumerate the sinks for us instead of blindly assuming that `0` is the one and only one to use.

I have to admit that I like the regular expression version more. I combined your code such that we have a free function (which I moved into `sound.py`) which also uses a regular expression.

The function `set_loudness` was still using `0` as the only sink, so I also enumerate over the sinks there.

It is merged into `develop`. Could you please check whether this works for you now?

**Comment by Aruee** [comment]
Seems to work fine for me... don't get an error after using your state from the develop branch. :+1:

**Pull request closed without merging**
